### PR TITLE
Overwriteable kafka settings

### PR DESCRIPTION
**Pull request by jordiclariana**
Improve kafka variables scopes and settings

Hi,

The main purpose of this PR is to be able to overwrite particular settings in Kafka server/producer without the need of rewrite the whole `server` and/or `producer` variable in your playbook or variables file.

It also "fixes" the variable scoping, renaming all non-starting with "kafka_" variables.
Take a look at the modified README.md, which tried to explain the changes and new variables usage.

I also added a `Version notes` section, as I think that this change breaks with previous versions and is important to explain how. I assume next version is 1.4.0 (as current latest tag is 1.3.0), but maybe if the change is too "radical" it could be named 2.0.0.

Lastly I fixed some conditions that throw error when the role is run in check_mode.

I tried all these changes and it worked well in my environment (obviously having in account the variables renaming). I run it against an already provisioned kafka server using 1.3.0 role version.

### CODE REVIEW

**Comment by jordiclariana** [comment]
Travis fails for versions <2.2.x.x. Can i change Travis config to stop supporting those versions? There been surpassed by 2.2 for a long time now. I will include a warning/notice in the README.md too and change the meta info.
Also, if we do that, then I guess that after this PR the version of the role should be changed to a new major: 2.0.0

What do you think?

**Comment by jaytaylor** [comment]
Hi Jordi,

This looks cool!  Can you squash the commits in this PR in order to maintain a clean commit history once it is merged into master?

**Comment by jordiclariana** [comment]
There you go!

**Comment by jordiclariana** [comment]
I just pushed a fix for `kafka_healthcheck_address` fact not well set when `kafka_server.host_name` is set to "".

**Comment by jaytaylor** [comment]
LGTM, thank you @jordiclariana !

**Pull request merged**
