### PR TITLE
Log and config convenience options

### PR DESCRIPTION
**Pull request by eladamitpxi**
switched host defs to be based on a collection
added option to disable the health check by using a 0 value for the timeout
fixing incorrect host list creation name
added misc server settings option
changing systemd to use the env file for it to be more robust
fixed log dir assignment to work from the ansible var
extracted log levels to role vars

### CODE REVIEW

**Comment by eladamitpxi** [comment]
is this repo still under maintenance?

**Comment by jaytaylor** [comment]
Yes, my apologies for not following up sooner.  I'll check this out later today or tomorrow.

**Comment by eladamitpxi** [comment]
cool, tx :)

**Comment by jaytaylor** [comment]
@eladamitpxi Thanks for your attention to detail and cleanup!

For some (probably unrelated reason) Kafka 2.x travis tests are still failing.  

LGTM for Kafka 1.x series.

**Comment by eladamitpxi** [comment]
my pleasure :)

**Pull request merged**
