### PR TITLE
use ansible_service_mgr instead of custom logic …

### PR DESCRIPTION
**Pull request by lhoss**
…(also fixes check mode in the install part)

Would be great @jaytaylor !
Assuming this gets merged, I will also resolve conflict with https://github.com/jaytaylor/ansible-kafka/pull/21

### CODE REVIEW

**Comment by jaytaylor** [comment]
Greetings @lhoss,

Are you able to rebase against current master?  The CI tests are now passing there, and assuming they pass with this commit I'll merge it.

**Comment by lhoss** [comment]
I rebased, and indeed the ansible 2.0.x tests (still) green 👍 
but the 1.9.x builds are failing due to the new `ansible_service_mgr` checks:
``` 
TASK: [ansible-kafka | Create upstart config] ********************************* 
fatal: [localhost] => error while evaluating conditional: ansible_service_mgr != 'systemd'
``` 
I will create a PR to give up any pre v2 support, instead test builds with recent 2.2.x and 2.4.2 I'ld suggest 👍

**Comment by jaytaylor** [comment]
@lhoss Fabulous :D

**Comment by lhoss** [comment]
yeah   ... and rebased this PR  on master, so the builds now passed :)
happy to get it merged  ... @jaytaylor 👍

**Comment by jaytaylor** [comment]
Thank you @lhoss.

**Pull request merged**
