### PR TITLE
Fix hard coded user/group in sysmted unit

### PR DESCRIPTION
**Pull request by kcdbaba**

### CODE REVIEW

**Comment by kcdbaba** [comment]
Can we please have a tag if this gets merged in?

**Comment by jaytaylor** [comment]
@fissurezone I'm happy to merge this, but the default group will need to be "kafka" rather than "root".

Once that's fixed I'm happy to merge and create a tag for you.

Best,
Jay

**Comment by kcdbaba** [comment]
@jaytaylor i dont think the package creates a group called kafka. will have to add that in. are you sure you want this?

**Comment by jaytaylor** [comment]
@fissurezone It's previously been working- looks like the user and group are created together [here](https://github.com/jaytaylor/ansible-kafka/blob/master/tasks/system.yml#L10):

    user: name={{ kafka_user }} system=yes group={{ kafka_group }}

So yeah, let's keep it the same unless there is a compelling reason to change it.

Best,
Jay

**Comment by jaytaylor** [comment]
Thanks @fissurezone !

**Comment by kcdbaba** [comment]
hey @jaytaylor, looks like you have a typo in the tag `v1,2.0`

**Comment by jaytaylor** [comment]
Thanks, fixed!

**Pull request merged**
